### ISSUE TITLE
【Android】-【5.5.892】：【sdk获取不到最新的用户自定义字段，必须重新登录IM才可以，非自定义字段可以立即生效】

### ISSUE THREAD

**Issue by jayoss152** [TencentCloud/TIMSDK#1023]
issue内容：

【当前现象】：sdk获取不到最新的用户自定义字段，必须重新登录IM才可以，非自定义字段可以立即生效
【集成包】：IMSDK
【机型】：所有
【之前版本有无此问题】：有
【有无日志或者描述、截图】：A用户更新用户的自定义字段时，用户B调用SDK查看A用户资料的自定义字段看到的还是以前的数据，推测是在本地有缓存，目前必须要B用户重新登录才能查看到A最新的数据，但标配字段如头像就可以立即生效。
【期望】A用户更改资料后，B用户调用SDK查看A的所有资料都是最新的。

**Comment by Tencent-Alice** [comment]
您好，根据您的问题
 1 该问题是偶现还是必现
2 请问A在更新完自己的自定义字段值后，A拉取自己的值是否是最新的
技术问题，欢迎交流，q2562367495 注明来意

**Comment by jayoss152** [comment]
1.必现
2.A使用sdk更新自己的自定义字段，再用sdk查更新的自定义字段是最新的
