### ISSUE TITLE
是否会支持单页面多实例

### ISSUE THREAD

**Issue by SmileLee123** [TencentCloud/TIMSDK#1037]
Web端是否会支持单页面，多实例。或者会开放tim-js-sdk源代码么？

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，这个暂不支持，后续暂无排期，请知悉
技术问题 欢迎交流 q2562367495 注明来意

**Comment by SmileLee123** [comment]
聊天记录查询之后会支持吗？

**Comment by SmileLee123** [comment]
> 您好，根据您的问题，这个暂不支持，后续暂无排期，请知悉
> 技术问题 欢迎交流 q2562367495 注明来意

您好，加好友
