### ISSUE TITLE
【Flutter】-【3.4.4】：【部分manager方法未作异步对待，导致无法进行异常应对、await等】

### ISSUE THREAD

**Issue by orenwang** [TencentCloud/TIMSDK#1074]
【当前现象】：部分manager方法未作异步对待，导致无法进行异常应对、await等
【集成包】：tencent_im_sdk_plugin
【机型】：与机型无关
【之前版本有无此问题】：历史版本存在同样问题
【有无日志或者描述、截图】：
举例1 - 异常应对
由 `MethodChannel` 主动抛异常，但业务侧没有任何办法 `catch` 该异常：
![image](https://user-images.githubusercontent.com/13847926/144962690-1f1ce72b-9577-4e1d-aec5-f64bfe4bd875.png)

举例2 - 业务进行await
移除消息监听器后，立即新增消息监听器，此时因业务侧没有任何办法对移除操作进行 `await`，而 `MethodChannel` 的表现均为异步，此时会存在“移除”未进行完毕而”新增“已经开始的可能：
![image](https://user-images.githubusercontent.com/13847926/144963327-5dc260c0-711f-477a-a81b-9a14bd4689ab.png)

**Comment by Tencent-Alice** [comment]
您好，这个是偶发还是常发，具体是ios端的问题吗，方便进一步定位
技术问题，欢迎交流 q2562367495 注明来意

**Comment by orenwang** [comment]
@Tencent-Alice 感谢回复。这个是Android/iOS端均常发的问题，是技术类型问题，限制了业务侧的处理方式；此外，我已经对代码进行小幅度修正并提了PR，可直接对 https://github.com/tencentyun/TIMSDK/pull/1075 进行处理即可。

**Comment by hexingcheng** [comment]
> @Tencent-Alice 感谢回复。这个是Android/iOS端均常发的问题，是技术类型问题，限制了业务侧的处理方式；此外，我已经对代码进行小幅度修正并提了PR，可直接对 #1075 进行处理即可。

收到我们下个版本修复一下。感谢！
