### ISSUE TITLE
customStickerPackageList can not be empty

### ISSUE THREAD

**Issue by liuzehnhang** [TencentCloud/TIMSDK#1141]
issue标题：customStickerPackageList can not be empty

  Failed assertion: line 91 pos 12: 'widget.customStickerPackageList.isNotEmpty'

【当前现象】：点击聊天页面表情按钮，表情按钮展示界面报错
【集成包】：下载的 flutter  uikit demo

**Comment by hexingcheng** [comment]
customStickerPackageList传一下即可，更多问题可以加入群788910197讨论

**Comment by jackbbhua** [comment]
![Uploading image.png…]()

demo里面已经传了!怎么处理呀
