### ISSUE TITLE
【react-native】看到什么版本都有 居然没有RN版本心酸。

### ISSUE THREAD

**Issue by jamninetyfive** [TencentCloud/TIMSDK#1143]
请问有计划做RN么？虽然只是做层bridge，对于你们不就是顺手撸一个的事儿嘛~

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，可以参考https://github.com/mengyou658/react-native-tencent-im-ui 
技术问题 欢迎交流 q2562367495 注明来意
