### ISSUE TITLE
【Flutter】-【tim_ui_kit  0.0.7】：【插件缺少该函数】

### ISSUE THREAD

**Issue by xianjianlf2** [TencentCloud/TIMSDK#1148]
【Flutter】-【tim_ui_kit 0.0.7】：【插件缺少该函数】 
【当前现象】：Flutter集成新版本TUIKit，报错，无法编译通过
![image](https://user-images.githubusercontent.com/53885024/164914218-4e146acf-8a77-44db-b32a-6432846c850b.png)
历史版本上面是有这个函数的：
tencent_im_sdk_plugin-3.9.2/lib/enum/utils.dart
![image](https://user-images.githubusercontent.com/53885024/164953597-07292a35-cff0-489c-b44e-5c4e39acac33.png)

**Comment by hexingcheng** [comment]
0.0.7依赖的3.9.2，看看你的tencent_im_sdk_plugin是不是升级到了最新

**Comment by hexingcheng** [comment]
或者升级uikit版本到0.0.8

**Comment by xianjianlf2** [comment]
升级之后就可以解决  谢谢

> 或者升级uikit版本到0.0.8
