### ISSUE TITLE
tim-js-friendship.js:1 Uncaught TypeError: Cannot assign to read only property 'lastTime' of object '#<Object>'

### ISSUE THREAD

**Issue by sunmoon1992** [TencentCloud/TIMSDK#1150]
tim-js-friendship.js:1 Uncaught TypeError: Cannot assign to read only property 'lastTime' of object '#<Object>'

web端 - TIM.VERSION: 2.18.2：
在选中某个会话作为当前会话之后，发出消息会报错：TIM 10:51:46.357:MessageModule._onSendMessageFailed error: {"message":"Cannot assign to read only property 'lastTime' of object '#<Object>'"} ，没找到原因，求助！！！

**Comment by sunmoon1992** [comment]
debug

**Comment by JunniL** [comment]
> tim-js-friendship.js:1 Uncaught TypeError: Cannot assign to read only property 'lastTime' of object '#'
> 
> web端 - TIM.VERSION: 2.18.2： 在选中某个会话作为当前会话之后，发出消息会报错：TIM 10:51:46.357:MessageModule._onSendMessageFailed error: {"message":"Cannot assign to read only property 'lastTime' of object '#'"} ，没找到原因，求助！！！



> tim-js-friendship.js:1 Uncaught TypeError: Cannot assign to read only property 'lastTime' of object '#'
> 
> web端 - TIM.VERSION: 2.18.2： 在选中某个会话作为当前会话之后，发出消息会报错：TIM 10:51:46.357:MessageModule._onSendMessageFailed error: {"message":"Cannot assign to read only property 'lastTime' of object '#'"} ，没找到原因，求助！！！

我也碰到这个问题，想请教下最后怎么解决或者说debug思路

**Comment by sunmoon1992** [comment]
JunniL ***@***.***>于2022年5月6日 周五下午11:05写道：

> tim-js-friendship.js:1 Uncaught TypeError: Cannot assign to read only
> property 'lastTime' of object '#'
>
> web端 - TIM.VERSION: 2.18.2： 在选中某个会话作为当前会话之后，发出消息会报错：TIM
> 10:51:46.357:MessageModule._onSendMessageFailed error: {"message":"Cannot
> assign to read only property 'lastTime' of object '#'"} ，没找到原因，求助！！！
>
> tim-js-friendship.js:1 Uncaught TypeError: Cannot assign to read only
> property 'lastTime' of object '#'
>
> web端 - TIM.VERSION: 2.18.2： 在选中某个会话作为当前会话之后，发出消息会报错：TIM
> 10:51:46.357:MessageModule._onSendMessageFailed error: {"message":"Cannot
> assign to read only property 'lastTime' of object '#'"} ，没找到原因，求助！！！
>
> 我也碰到这个问题，想请教下最后怎么解决或者说debug思路
>

你用的react嘛，如果是react，会话的数据流赋值的时候不要用解构

**Comment by JunniL** [comment]
> 
也用得react，好像确实。之前reducers里面解构赋值，跑本地就不会报错，打包之后跑就直接报这个了。感谢指路🙇‍
