### ISSUE TITLE
地图sdk在使用中出现如下报错

### ISSUE THREAD

**Issue by zhaobinbin2019** [TencentCloud/TIMSDK#1165]
版本：
  flutter:2.10.5
  tim_ui_kit: ^0.0.8 #聊天
  tim_ui_kit_calling_plugin: ^0.1.5 #tim视频通话
  tim_ui_kit_lbs_plugin: ^1.1.1 #lbs定位
  flutter_baidu_mapapi_map: ^3.1.0+1 #百度地图
  flutter_baidu_mapapi_base: ^3.1.0 #百度地图
  flutter_baidu_mapapi_search: ^3.1.0 #百度地图
  flutter_baidu_mapapi_utils: ^3.1.0+1 #百度地图
  flutter_bmflocation: ^3.0.0 #百度地图
错误说明：
发送地图消息后，打开地图消息报错。
报错日志：

I/EGL_adreno( 5385): eglCreateContext request GLES major-version=2
E/EGL_adreno( 5385): tid 5428: eglSurfaceAttrib(1328): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer( 5385): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa80b5120, error=EGL_BAD_MATCH
D/EGL_adreno( 5385): eglCreateContext: 0x8fb2ad60: maj 3 min 1 rcv 4
D/EGL_adreno( 5385): eglMakeCurrent: 0xb6f26140: ver 3 1 (tinfo 0xba5aa800)
D/EGL_adreno( 5385): eglMakeCurrent: 0x8fb2ad60: ver 3 1 (tinfo 0xa806d5a0)
D/HostConnection( 5385): ExtendedRCEncoderContext GL_VERSION return OpenGL ES 3.1
E/BitmapFactory( 5385): Unable to decode stream: java.lang.NullPointerException
W/System.err( 5385): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.recycle()' on a null object reference      
W/System.err( 5385):    at com.baidu.mapapi.map.BitmapDescriptorFactory.fromAsset(BitmapDescriptorFactory.java:11)
W/System.err( 5385):    at com.baidu.bmfmap.map.overlayhandler.MarkerHandler.setMarkerOptions(MarkerHandler.java:252)
W/System.err( 5385):    at com.baidu.bmfmap.map.overlayhandler.MarkerHandler.addMarkerImp(MarkerHandler.java:169)
W/System.err( 5385):    at com.baidu.bmfmap.map.overlayhandler.MarkerHandler.addMarker(MarkerHandler.java:114)
W/System.err( 5385):    at com.baidu.bmfmap.map.overlayhandler.MarkerHandler.handlerMethodCall(MarkerHandler.java:57)
W/System.err( 5385):    at com.baidu.bmfmap.map.overlayhandler.OverlayHandlerFactory.dispatchMethodHandler(OverlayHandlerFactory.java:162)
W/System.err( 5385):    at com.baidu.bmfmap.BMFMapController.onMethodCall(BMFMapController.java:126)
W/System.err( 5385):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err( 5385):    at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
W/System.err( 5385):    at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
W/System.err( 5385):    at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(lambda)
W/System.err( 5385):    at android.os.Handler.handleCallback(Handler.java:751)
W/System.err( 5385):    at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err( 5385):    at android.os.Looper.loop(Looper.java:154)
W/System.err( 5385):    at android.app.ActivityThread.main(ActivityThread.java:6153)
W/System.err( 5385):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 5385):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
W/System.err( 5385):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
D/GLRenderControl( 5385): mRenderer.onSurfaceCreated
D/GLRenderControl( 5385): mRenderer.onSurfaceChanged
I/flutter ( 5385): mapDidLoad-地图加载完成
![Screenshot_20220515-121400](https://user-images.githubusercontent.com/51144625/168456928-7889b746-a1c5-4502-b131-971217c50012.png)

![Screenshot_20220515-121310](https://user-images.githubusercontent.com/51144625/168456904-d84a758a-47ec-48fe-919a-d1a9e382fafa.png)

**Comment by Andy-Home** [comment]
我也遇到过同样的问题，刚刚解决了。我的问题时引用的Marker资源没有导入进来，在Flutter 的 pubspec.yaml配置对应文件

**Comment by zhaobinbin2019** [comment]
> 我也遇到过同样的问题，刚刚解决了。我的问题时引用的Marker资源没有导入进来，在Flutter 的 pubspec.yaml配置对应文件

谢谢，我先试试

**Comment by zhaobinbin2019** [comment]
> 我也遇到过同样的问题，刚刚解决了。我的问题时引用的Marker资源没有导入进来，在Flutter 的 pubspec.yaml配置对应文件

谢谢，我先试试
