### ISSUE TITLE
安卓平台tim_ui_kit 0.0.9 版本：发送图片时报错

### ISSUE THREAD

**Issue by clstech** [TencentCloud/TIMSDK#1175]
【当前现象】：聊天界面发送图片时报错，发送完成后正常
【集成包】：tim_ui_kit
【机型】：小米11
【之前版本有无此问题】：之前版本未在Flutter 3.0中使用过
【有无日志或者描述、截图】：Debug模式下提示
`
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building Builder(dirty):
Null check operator used on a null value

The relevant error-causing widget was: 
  TIMUIKitChat TIMUIKitChat:file:///Users/chenchun/StudioProjects/sheep/lib/pages/message/components/chat.dart:20:12
When the exception was thrown, this was the stack: 
#0      Chat.build.<anonymous closure> (package:sheep/pages/message/components/chat.dart:46:64)
#1      _TIMUIKItHistoryMessageListItemState._messageItemBuilder (package:tim_ui_kit/ui/views/TIMUIKitChat/TIMUIKItMessageList/tim_uikit_chat_history_message_list_item.dart:535:62)
#2      _TIMUIKItHistoryMessageListItemState._getMessageItemBuilder (package:tim_ui_kit/ui/views/TIMUIKitChat/TIMUIKItMessageList/tim_uikit_chat_history_message_list_item.dart:676:16)
#3      _TIMUIKItHistoryMessageListItemState.build.<anonymous closure> (package:tim_ui_kit/ui/views/TIMUIKitChat/TIMUIKItMessageList/tim_uikit_chat_history_message_list_item.dart:945:46)
#4      Builder.build (package:flutter/src/widgets/basic.dart:7371:48)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4876:49)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
...     Normal element mounting (10 frames)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#20     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#21     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#23     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#24     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (10 frames)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#35     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#36     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (27 frames)
#63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#64     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#65     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (77 frames)
#142    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:3545:20)
#144    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1265:37)
#145    SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1169:35)
#146    Iterable.forEach (dart:core/iterable.dart:325:35)
#147    SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1213:24)
#148    SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1146:7)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#150    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#152    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#153    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#154    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#155    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#157    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#158    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#159    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#160    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#161    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#162    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#164    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#165    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#166    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#168    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#171    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#172    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#173    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#174    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#175    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#177    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#178    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#179    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#180    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#181    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#182    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#184    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#185    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#187    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#188    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#189    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#191    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#192    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#193    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#194    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#195    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#196    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#197    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#198    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#199    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#201    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#202    StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#203    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#204    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#205    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#206    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#207    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#208    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#209    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#210    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#212    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#213    StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#214    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#215    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#216    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#217    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#218    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#219    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#220    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#221    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#222    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#223    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#224    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#225    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#226    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#227    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#228    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#229    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#230    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#231    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#232    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#233    StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#234    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#235    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#236    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#237    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#238    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#239    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#240    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#241    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#242    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#243    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#244    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#245    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#246    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#247    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#248    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#249    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#250    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#251    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#252    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#253    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#254    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#256    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#257    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#258    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#259    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#260    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#261    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#262    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#263    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#264    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#265    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#266    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222:14)
#267    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#268    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#269    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#270    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#271    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#272    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#273    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#274    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#275    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#276    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#277    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#278    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#279    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#280    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#281    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#282    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#283    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#284    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#285    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#286    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#287    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#288    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#289    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#290    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#291    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#292    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#293    ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#294    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#295    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#296    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#297    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#298    StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#299    Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#300    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#301    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#302    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#303    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#304    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#305    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#306    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#307    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#311    _invoke (dart:ui/hooks.dart:151:10)
#312    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#313    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
I/flutter (29474): message progress: 0
I/flutter (29474): message progress: 18
I/flutter (29474): message progress: 36
I/flutter (29474): message progress: 74
I/flutter (29474): message progress: 100
I/imsdk   (29474): TIM: |-file_downloader.cpp:114                 HandleDownloadProgress                  |downloading|id:5|4096/56011
I/imsdk   (29474): TIM: |-file_downloader.cpp:111                 HandleDownloadProgress                  |downloading|id:5|56011/56011
I/imsdk   (29474): TIM: |-file_downloader.cpp:102                 HandleDownloadComplete                  |end download|id:5 success!
I/imsdk   (29474): TIM: |-file_downloader.cpp:81                  Cancel                                  |cancel download|id:5
E/imsdk   (29474): TIM: |-http_client.cpp:128                     Cancel                                  |current http client is not running
I/imsdk   (29474): TIM: |-file_downloader.cpp:111                 HandleDownloadProgress                  |downloading|id:2|421459/421459
I/imsdk   (29474): TIM: |-file_downloader.cpp:102                 HandleDownloadComplete                  |end download|id:2 success!
I/imsdk   (29474): TIM: |-file_downloader.cpp:81                  Cancel                                  |cancel download|id:2
E/imsdk   (29474): TIM: |-http_client.cpp:128                     Cancel                                  |current http client is not running

`

**Comment by RoleWong** [comment]
抱歉没有复现出来，辛苦加入QQ群聊788910197，反馈下复现路径

**Comment by clstech** [comment]
好的谢谢
