### ISSUE TITLE
Android标准版5.1.66 取消禁言后，禁言列表数据没更新

### ISSUE THREAD

**Issue by werildev** [TencentCloud/TIMSDK#1190]
指定用户 setForbidden 设置为false ，通过getForbidden获取的禁言列表中还存在该用户信息

**Comment by vinsonswang** [comment]
IMSDK 没有提供禁言列表的功能，看下是否是 app 的业务层实现的。
另外标准版已经不维护了，麻烦升级到增强版哈。
