### ISSUE TITLE
不能打包

### ISSUE THREAD

**Issue by lydlovezjr** [TencentCloud/TIMSDK#1197]
<img width="919" alt="微信截图_20220708173515" src="https://user-images.githubusercontent.com/19246347/177963615-473dfacf-073e-4aa2-82d2-b3d0bd7f03bb.png">
Execution failed for task ':app:lintVitalAnalyzeRelease'.
> Could not resolve all files for configuration ':app:releaseCompileClasspath'.
   > Failed to transform out.aar (project :tuichat) to match attributes {artifactType=android-lint-exploded-aar, com.android.build.api.attributes.AgpVersionAttr=7.1.3, com.android.build.api.attributes.BuildTypeAttr=release, com.android.build.gradle.internal.attributes.VariantAttr=release, org.gradle.usage=java-api}.
      > Execution failed for ExtractAarTransform: D:\MyAllProject\PnpProject\cctc_android_app\cctc\TUIKit\TUIChat\tuichat\build\intermediates\local_aar_for_lint\release\out.aar.
         > malformed input off : 15, length : 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by Chen-Xi-g** [comment]
从 Gradle 缓存文件夹中删除损坏的 .aar试试

**Comment by lfclfc** [comment]
@lydlovezjr 解決了嗎兄弟，我也遇到這個問題了
