### ISSUE TITLE
群禁言成员后、然后删除禁言、然后再次重新进入被删除禁言的用户还存在

### ISSUE THREAD

**Issue by xiaoliang-cn** [TencentCloud/TIMSDK#1200]
版本 tim_ui 0.0.9
tencent_im_sdk_plugin: ^4.0.7
flutter sdk ： 3.0.4

第一个问题：主要是否禁言是判断当前群成员信息的muteTime字段、但是滑动删除后本地修改成功，但是从V2MesageManager实例获取muteTime不等于0，是否远程服务器未修改导致？

第二个问题：设置群全体禁言，成员未收到禁言字段isAllMuted的更改，需要重新关闭app再进进入才会收到更新后的信息。
```dart
 if (widget.selectedConversation.groupID != null) {
      ImHelper.v2timManager.getGroupManager().getGroupMembersInfo(
          groupID: widget.selectedConversation.groupID!,
          memberList: [ImHelper.userALLImInfo.userID!]).then((value) {
        Logger().e(value.data![0].toJson());
      });

      ImHelper.v2timManager.getGroupManager().getGroupsInfo(
          groupIDList: [widget.selectedConversation.groupID!]).then((value) {
        if (value.code == 0) {
          if (value.data != null) {
            var groupInfo = value.data![0];
            Logger().e(groupInfo.toJson());
            if (groupInfo.groupInfo!.role != 400) {
              isAllMuted = groupInfo.groupInfo?.isAllMuted ?? false;
              setState(() {});
            }
            // Logger().e(groupInfo.toJson());
          }
        }
      });
    }
```
这是代码例子，我门每次进入会话都会重新获取群信息。

**Comment by xiaoliang-cn** [comment]
发现报错：error_code:7011|error_message:not found 但是不知道如何处理，也不知道这个报错是否和问题相关，补充的是解除禁言后返回的response 是 状态是0 des 是ok

**Comment by hexingcheng** [comment]
> 版本 tim_ui 0.0.9 tencent_im_sdk_plugin: ^4.0.7 flutter sdk ： 3.0.4
> 
> 第一个问题：主要是否禁言是判断当前群成员信息的muteTime字段、但是滑动删除后本地修改成功，但是从V2MesageManager实例获取muteTime不等于0，是否远程服务器未修改导致？
> 
> 第二个问题：设置群全体禁言，成员未收到禁言字段isAllMuted的更改，需要重新关闭app再进进入才会收到更新后的信息。
> 
> ```dart
>  if (widget.selectedConversation.groupID != null) {
>       ImHelper.v2timManager.getGroupManager().getGroupMembersInfo(
>           groupID: widget.selectedConversation.groupID!,
>           memberList: [ImHelper.userALLImInfo.userID!]).then((value) {
>         Logger().e(value.data![0].toJson());
>       });
> 
>       ImHelper.v2timManager.getGroupManager().getGroupsInfo(
>           groupIDList: [widget.selectedConversation.groupID!]).then((value) {
>         if (value.code == 0) {
>           if (value.data != null) {
>             var groupInfo = value.data![0];
>             Logger().e(groupInfo.toJson());
>             if (groupInfo.groupInfo!.role != 400) {
>               isAllMuted = groupInfo.groupInfo?.isAllMuted ?? false;
>               setState(() {});
>             }
>             // Logger().e(groupInfo.toJson());
>           }
>         }
>       });
>     }
> ```
> 
> 这是代码例子，我门每次进入会话都会重新获取群信息。

问题二：isAllMuted的通知需要在控制台配置，客户端才会在groupInfoChange的回调中收到。uikit 0.1.2中包含了群会话禁言的相关处理，可以更新看看
问题一：是否禁言有两个字段，muteTime和muteUtil，看接口返回哪个就用哪个

进群788910197，专门处理tim flutter sdk相关问题。

**Comment by xiaoliang-cn** [comment]
加群审核一直没有回复，已经超过48小时了。你们处理问题的速度为什么那么低效呢？ 你们这套im系统本来就是收费系统，但是提供的服务和解决问题的效率实在太慢了。

**Comment by hexingcheng** [comment]
> 加群审核一直没有回复，已经超过48小时了。你们处理问题的速度为什么那么低效呢？ 你们这套im系统本来就是收费系统，但是提供的服务和解决问题的效率实在太慢了。

你是不是没申请对？

**Comment by xiaoliang-cn** [comment]
qq群 已经申请了两次了 填写了两次sdk appid 了
