### ISSUE TITLE
Flutter ios IM 聊天申请相机权限，已在设置打开「相机」权限，每次点击还提示「无权限并跳转设置」，

### ISSUE THREAD

**Issue by kaiddi** [TencentCloud/TIMSDK#1203]
issue标题：Flutter ios IM 聊天申请相机权限，已在设置打开「相机」权限，每次点击还提示「无权限并跳转设置」，

【Flutter ios】-【 tim_ui_kit: 0.1.2】：
issue内容：
Flutter ios IM 聊天申请相机权限，已在设置打开「相机」权限，每次点击还提示「无权限并跳转设置」，

【集成包】：IMSDK
【机型】：iPhone 7

**Comment by hexingcheng** [comment]
> issue标题：Flutter ios IM 聊天申请相机权限，已在设置打开「相机」权限，每次点击还提示「无权限并跳转设置」，
> 
> 【Flutter ios】-【 tim_ui_kit: 0.1.2】： issue内容： Flutter ios IM 聊天申请相机权限，已在设置打开「相机」权限，每次点击还提示「无权限并跳转设置」，
> 
> 【集成包】：IMSDK 【机型】：iPhone 7

请升级到tim_ui_kit最新版本进行测试验证
