### ISSUE TITLE
项目无法依赖

### ISSUE THREAD

**Issue by QixianWu** [TencentCloud/TIMSDK#1212]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDoctorDebugAarMetadata'.
> Could not resolve all files for configuration ':app:doctorDebugRuntimeClasspath'.
   > Could not find com.github.shaoshuai904:RecordWav:1.0.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/shaoshuai904/RecordWav/1.0.2/RecordWav-1.0.2.pom
       - https://repo.maven.apache.org/maven2/com/github/shaoshuai904/RecordWav/1.0.2/RecordWav-1.0.2.pom
       - https://storage.flutter-io.cn/download.flutter.io/com/github/shaoshuai904/RecordWav/1.0.2/RecordWav-1.0.2.pom
       - https://jcenter.bintray.com/com/github/shaoshuai904/RecordWav/1.0.2/RecordWav-1.0.2.pom
       - https://jitpack.io/com/github/shaoshuai904/RecordWav/1.0.2/RecordWav-1.0.2.pom
     Required by:
         project :app > project :flutter_plugin_record_plus

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 11s
Exception: Gradle task assembleDoctorDebug failed with exit code 1

```

**Comment by chengw32** [comment]
我也是，搜了下都没人提过  ，难道其他人都没问题 吗  [旺柴]

**Comment by QixianWu** [comment]
> 

hhh，有缓存的话就没事。我之前也没问题～～

**Comment by hexingcheng** [comment]
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:checkDoctorDebugAarMetadata'.
> > Could not resolve all files for configuration ':app:doctorDebugRuntimeClasspath'.
>    > Could not find com.github.shaoshuai904:RecordWav:1.0.2.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/com/github/shaoshuai904/RecordWav/1.0.2/RecordWav-1.0.2.pom
>        - https://repo.maven.apache.org/maven2/com/github/shaoshuai904/RecordWav/1.0.2/RecordWav-1.0.2.pom
>        - https://storage.flutter-io.cn/download.flutter.io/com/github/shaoshuai904/RecordWav/1.0.2/RecordWav-1.0.2.pom
>        - https://jcenter.bintray.com/com/github/shaoshuai904/RecordWav/1.0.2/RecordWav-1.0.2.pom
>        - https://jitpack.io/com/github/shaoshuai904/RecordWav/1.0.2/RecordWav-1.0.2.pom
>      Required by:
>          project :app > project :flutter_plugin_record_plus
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 11s
> Exception: Gradle task assembleDoctorDebug failed with exit code 1
> ```

进群：788910197，我们来看看

**Comment by hexingcheng** [comment]
> 我也是，搜了下都没人提过 ，难道其他人都没问题 吗 [旺柴]

进群：788910197，我们来看看

**Comment by wangyuuuu** [comment]
怎么解决的 我flutter 2.8.1    tim_ui_kit: ^0.0.8
现在报这个问题？怎么解决的

**Comment by wangyuuuu** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.shaoshuai904:RecordWav:1.0.1.
     Searched in the following locations:
       - https://maven.aliyun.com/repository/google/com/github/shaoshuai904/RecordWav/1.0.1/RecordWav-1.0.1.pom
       - https://maven.aliyun.com/repository/jcenter/com/github/shaoshuai904/RecordWav/1.0.1/RecordWav-1.0.1.pom
       - https://maven.aliyun.com/repository/public/com/github/shaoshuai904/RecordWav/1.0.1/RecordWav-1.0.1.pom
       - https://developer.huawei.com/repo/com/github/shaoshuai904/RecordWav/1.0.1/RecordWav-1.0.1.pom
       - https://storage.flutter-io.cn/download.flutter.io/com/github/shaoshuai904/RecordWav/1.0.1/RecordWav-1.0.1.pom
       - https://dl.google.com/dl/android/maven2/com/github/shaoshuai904/RecordWav/1.0.1/RecordWav-1.0.1.pom
       - https://repo.maven.apache.org/maven2/com/github/shaoshuai904/RecordWav/1.0.1/RecordWav-1.0.1.pom
       - https://jcenter.bintray.com/com/github/shaoshuai904/RecordWav/1.0.1/RecordWav-1.0.1.pom
       - https://jitpack.io/com/github/shaoshuai904/RecordWav/1.0.1/RecordWav-1.0.1.pom
     Required by:
         project :app > project :flutter_plugin_record

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 33s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by chianglife** [comment]
请问解决了吗，我也遇到了相同的问题

**Comment by QixianWu** [comment]
> 请问题解决了吗，我也遇到了相同的问题

这个问题是，插件需要的原生库无法依赖。只能等插件作者解决或者使用插件的其他版本。而且上面作者也留了群联系方式，你可以进去咨询下。
