### ISSUE TITLE
Android -6.6.3002   TUICore  模块 EventManager 类的 TAG 写错了

### ISSUE THREAD

**Issue by EmperorBoBo** [TencentCloud/TIMSDK#1252]
为了更好的了解您使用TIMSDK所遇到的问题，方便快速有效定位解决TIMSDK问题，希望您按如下模板反馈issue，方便我们尽快解决您的问题，目前有TUIKIT集成包，和IMSDK集成包，注意说明是引入了哪个集成包的问题。另外如果需要补充更多信息请及时更新，否则可能被作为无效问题而关闭，这个等待期一般是10天。

issue标题：

【Android】-【6.6.3002】：【TUICore  模块 EventManager 类的 TAG 写错了】
issue内容：

【当前现象】：TUICore  模块 EventManager 类的 TAG 写错了
【集成包】：IMSDK  TUICore
【机型】：Android Google pixel4
【之前版本有无此问题】： 无
【有无日志或者描述、截图】：无

**Comment by vinsonswang** [comment]
已修改，感谢反馈
