### ISSUE TITLE
TUINavigationController 是哪个傻逼写的？？有这样写代码的？

### ISSUE THREAD

**Issue by zhulmin** [TencentCloud/TIMSDK#1265]
为了更好的了解您使用TIMSDK所遇到的问题，方便快速有效定位解决TIMSDK问题，希望您按如下模板反馈issue，方便我们尽快解决您的问题，目前有TUIKIT集成包，和IMSDK集成包，注意说明是引入了哪个集成包的问题。另外如果需要补充更多信息请及时更新，否则可能被作为无效问题而关闭，这个等待期一般是10天。

issue标题：

ios 

TUINavigationController 能用吗？这写的什么代码？

**Comment by HuangFeiPeng** [comment]
喷的这么狠吗 哈哈

**Comment by huangqin214** [comment]
这个问题最后是怎么绕过的，我也遇到了 @zhulmin

**Comment by zhoustarstar** [comment]
这个最后怎么解决的呢，请问
