### ISSUE TITLE
ios Demo 清空会话未读数 -onTotalUnreadMessageCountChanged 不回调

### ISSUE THREAD

**Issue by ygg29** [TencentCloud/TIMSDK#1287]
【iOS】-【6.9.3557】

SDK  调用方法 -markC2CMessage 清空会话未读数，但是方法 -onTotalUnreadMessageCountChanged 不回调

【当前现象】：方法 -onTotalUnreadMessageCountChanged 不回调
【集成包】：IMSDK
【机型】：iPhone 12 mini

**Comment by Tencent-Alice** [comment]
HI 根据您的问题可以描述下业务场景， 这个是否是必现呢 ，可以提供下其相关信息 ，方便进一步排查 
技术问题 欢迎交流 Q2562367495 注明来意

**Comment by Tencent-Alice** [comment]
https://cloud.tencent.com/document/product/269/77559#.E6.B8.85.E7.A9.BA.E4.BC.9A.E8.AF.9D.E6.9C.AA.E8.AF.BB.E6.B6.88.E6.81.AF.E6.95.B0 可以参考下
