### ISSUE TITLE
请问WebIM v1.7.x 的文档去哪了

### ISSUE THREAD

**Issue by goodhzy** [TencentCloud/TIMSDK#1294]
官网文档说的地址https://github.com/TencentCloud/TIMSDK/tree/master/H5/v1.7.x进入404，请问在哪可以看到之前的旧文档
![image](https://user-images.githubusercontent.com/38948033/206945408-60078f33-cb37-432e-8858-8dd60a7e05c2.png)

**Comment by Tencent-Alice** [comment]
HI 根据您的问题，WebIM v1.7.x 的文档已从官网下线，在 github 存有备份。您可以在github上查看：
https://web.sdk.qcloud.com/im/doc/zh-cn/tutorial-01-faq.html  
技术问题 欢迎交流 Q2562367495 注明来意
