### ISSUE TITLE
视频消息没有封面图

### ISSUE THREAD

**Issue by oushouyun** [TencentCloud/TIMSDK#1319]
Android-uniapp】-【2.17】：【视频信息没有封面图】

 这个DEMO应该更新下APP.vue，之前提交工单才知道sdk需要2.17以上，tim-upload-plugin插件上传视频才有封面，而且需要在video-element中添加snapshotUrl的背景图才能出封面图。

期望：更新demo在uniapp-Android环境下有视频信息的封面图

**Comment by Tencent-Alice** [comment]
您好  更新demos事项已反馈 ，感谢。  
技术问题 欢迎交流 Q2562367495 注明来意

**Comment by oushouyun** [comment]
我在发呆，现在不在。你若更呆，就往下看。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by oushouyun** [comment]
我在发呆，现在不在。你若更呆，就往下看。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
