### ISSUE TITLE
Android targetSdkVersion 31之上，所有<receiver>都添加了android:exported=“true” 还是报错

### ISSUE THREAD

**Issue by petersom** [TencentCloud/TIMSDK#1320]
【Android】-【6.9.3557 】：【Android targetSdkVersion 31之上，所有<receiver>都添加了android:exported=“true” 还是报错】
【集成包】：TUIKIT/TUIOfflinePush
【当前现象】：所有<receiver>都添加了android:exported=“true” 还是报错
【机型】：如华为Mate 20
【之前版本有无此问题】：有
【有无日志或者截图】：
android:exported needs to be explicitly specified for <receiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by chengqw** [comment]
// xiaomi
    implementation "com.tencent.tpns:xiaomi:1.3.7.2-release"
 // huawei
    implementation 'com.tencent.tpns:huawei:1.3.7.2-release'
    implementation 'com.huawei.hms:push:6.7.0.300'

请按照如上方法升级下推送包再试试

**Comment by Bruce-zxy** [comment]
> // xiaomi implementation "com.tencent.tpns:xiaomi:1.3.7.2-release" // huawei implementation 'com.tencent.tpns:huawei:1.3.7.2-release' implementation 'com.huawei.hms:push:6.7.0.300'
> 
> 请按照如上方法升级下推送包再试试

升级以后要注意hms:push的permission覆盖的问题，否则会报错：
```bash
Manifest merger failed : Attribute permission#com.daoing.client.permission.PROCESS_PUSH_MSG@protectionLevel value=(signatureOrSystem) from [:react-native-tim-push] AndroidManifest.xml:18:9-52
        is also present at [com.huawei.hms:push:6.7.0.300] AndroidManifest.xml:11:9-44 value=(signature).
        Suggestion: add 'tools:replace="android:protectionLevel"' to <permission> element at AndroidManifest.xml:16:5-18:55 to override.
```

添加了tools:replace="android:protectionLevel"以后就可以正常build了

![image](https://user-images.githubusercontent.com/22904758/231445517-5ab857d1-20a7-4ff1-b5f8-fe381375dca6.png)
