### ISSUE TITLE
[iOS]-[7.0.3754]：【集成IMSDK后打包上架报错：ITMS-90057】

### ISSUE THREAD

**Issue by Kanagizhe** [TencentCloud/TIMSDK#1321]
模拟器和真机都可以正常运行，打包也正常生成了IPA文件，但是提交审核时报错，报错信息如下：
ITMS-90057: The bundle 'Payload/[XXX.app/Frameworks/TUIChat.framework](http://dorado.app/Frameworks/TUIChat.framework)' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring

ITMS-90057: The bundle 'Payload/[XXX.app/Frameworks/TUIContact.framework](http://dorado.app/Frameworks/TUIContact.framework)' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring

ITMS-90057: The bundle 'Payload/[XXX.app/Frameworks/TUIConversation.framework](http://dorado.app/Frameworks/TUIConversation.framework)' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring

ITMS-90057: The bundle 'Payload/[XXX.app/Frameworks/TUICore.framework](http://dorado.app/Frameworks/TUICore.framework)' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring

**Comment by Tencent-Alice** [comment]
HI 根据您的问题，这个是接入的native端的iOSSDK是么， podfile文件use_frameworks!
这个注释掉    技术问题 欢迎交流 Q2562367495 注明来意
