### ISSUE TITLE
【HarmonyOS】-【8.2.6325】：【会话类V2TIMConversation中的lastMessage中的customElem是空的】

### ISSUE THREAD

**Issue by lcrep** [TencentCloud/TIMSDK#1418]
【当前现象】：会话类V2TIMConversation中的lastMessage的elemType是自定义消息时，customElem没有数据，Android版和web版同一条数据确定有自定义数据
【机型】：模拟器

**Comment by ancircle0** [comment]
@lcrep getConversationListByFilter 这个api 返回的V2TIMConversation[] 的customElem.data 是没数据的  ，带佬用的哪个apih获取的会话列表

**Comment by lcrep** [comment]
@ancircle0 也是这个

**Comment by ancircle0** [comment]
@lcrep 谢谢带佬
