### ISSUE TITLE
【web】-【2.7.7】：【createGroup.then报错】

### ISSUE THREAD

**Issue by 490626721** [TencentCloud/TIMSDK#819]
【当前现象】：使用SDK的createGroup.then时报错
【集成包】：IMSDK
【机型】：pc
【之前版本有无此问题】：不清楚
【有无日志或者描述、截图】：
ncaught TypeError: Cannot read property 'then' of undefined

复制文档操作的代码
// 创建好友工作群
        let promise = tim.createGroup({
            type: TIM.TYPES.GRP_MEETING,//群组类型
            name: 'WebSDK',//必填，群组名称，最长30字节
            groupID: this.roomId_,//群组 ID。不填该字段时，会自动为群组创建一个唯一的群 ID
            introduction: '11111111111111111111111111111',//群简介，最长240字节
            notification: '222222222222',//群公告，最长300字节
        });
        promise.then(function (imResponse) { // 创建成功
            console.log(imResponse.data.group); // 创建的群的资料
        }).catch(function (imError) {
            console.warn('createGroup error:', imError); // 创建群组失败的相关信息
        });

**Comment by xhwgood** [comment]
老哥，你解决了吗？我在小程序里调用`getConversationProfile`方法时遇到了类似的问题，但直接`console.log`的话是存在的

**Comment by 490626721** [comment]
> 老哥，你解决了吗？我在小程序里调用`getConversationProfile`方法时遇到了类似的问题，但直接`console.log`的话是存在的

如果是jquery需要把这部分逻辑代码写到他提供的演示代码那几个关键JS内，如果是VUE没问题的话就要检查其他的了

**Comment by xhwgood** [comment]
项目里没用jquery，但其他的也实在检查不出来啊……

**Comment by 490626721** [comment]
> 项目里没用jquery，但其他的也实在检查不出来啊……

这个就不太清楚了，建议去腾讯云提工单，那样处理会快点，这边基本没人管的
