### ISSUE TITLE
是否支持插入本地IM消息

### ISSUE THREAD

**Issue by FlameLee** [TencentCloud/TIMSDK#964]
是否支持消息只存储到本地，无需发送到服务器（不需要对方接受），用于显示欢迎语等需求，在文档没有找到相关api，请问是否支持这种本地操作？如果暂不支持的话是否有后续的规划及排期？

**Comment by Tencent-Alice** [comment]
您好 目前 可以通过单聊消息发送之前的回调来获取到对应的信息并进行拦截保存即可，暂时没有相关的API为您提供
单聊消息之前的回调拦截：
https://cloud.tencent.com/document/product/269/1632#.E5.BA.94.E7.AD.94.E5.8C.85.E7.A4.BA.E4.BE.8B.EF.BC.88.E7.A6.81.E6.AD.A2.E5.8F.91.E8.A8.80.EF.BC.89 

![image](https://user-images.githubusercontent.com/74762384/110434088-557fad00-80ec-11eb-8418-542439068f1f.png)
技术问题 欢迎交流 Q2562367495 注明来意
