### ISSUE TITLE
【Android】- 【4.9.1】: 服务端下载的消息记录，手机端如何解析（需求：缓存七天以前的历史消息）

### ISSUE THREAD

**Issue by ludaxin6** [TencentCloud/TIMSDK#979]
【当前现象】：
**手机端对加载七天前的消息从我们服务端来，如何解析历史消息？**
**碰到的问题是如何构建 V2TIMMessage 对象，sdk已经封装死了，也没有找到构建的方法，大佬们求解**
【集成包】：TUIKIT
【机型】：如小米5c
【之前版本有无此问题】：没有接触之前版本
【有无日志或者描述、截图】：
即时通信IM下载最近消息记录-服务端API-文档：https://cloud.tencent.com/document/product/269/1650
根据以上文档，我们服务端将需要的历史消息下载到服务端。
服务端返回的历史消息数据：
[
            {
                "msgId": "1f39fd8f7a534fa38faee3a6e6c83134",
                "fromAccount": "9b092c6a322f2490ad2c341f6da1a79a",
                "toAccount": null,
                "groupId": "cb8864887f30cb9aede7dbd21c182b4e",
                "msgSeq": 88,
                "msgRandom": null,
                "msgTimestamp": 1616467662,
                "historyFileId": "510b9bd144184c728c4c4fe93f8b85af",
                "createTime": null,
                "updateTime": null,
                "msgBodyJson": null,
                "msgBody": [
                    {
                        "msgType": "TIMTextElem",
                        "msgContent": {
                            "Text": "Ni has"
                        }
                    }
                ]
            },
            {
                "msgId": "a0df004aa9c54bc19d62ade6230601b6",
                "fromAccount": "9b092c6a322f2490ad2c341f6da1a79a",
                "toAccount": null,
                "groupId": "cb8864887f30cb9aede7dbd21c182b4e",
                "msgSeq": 87,
                "msgRandom": null,
                "msgTimestamp": 1616467611,
                "historyFileId": "510b9bd144184c728c4c4fe93f8b85af",
                "createTime": null,
                "updateTime": null,
                "msgBodyJson": null,
                "msgBody": [
                    {
                        "msgType": "TIMFileElem",
                        "msgContent": {
                            "Download_Flag": 2,
                            "FileName": "发票.pdf",
                            "UUID": "1400415139_9b092c6a322f2490ad2c341f6da1a79a_55f7e925e5b572aafd7f36665c3ecbd9.pdf",
                            "Url": "https://files.csd.test.v2db.com/noauth/noauth_1616654008569_2021-03-25_443.pdf",
                            "FileSize": 40805
                        }
                    }
                ]
            },
            {
                "msgId": "96dc169881b04105a3d58d710f1cf6ac",
                "fromAccount": "9b092c6a322f2490ad2c341f6da1a79a",
                "toAccount": null,
                "groupId": "cb8864887f30cb9aede7dbd21c182b4e",
                "msgSeq": 86,
                "msgRandom": null,
                "msgTimestamp": 1616467495,
                "historyFileId": "510b9bd144184c728c4c4fe93f8b85af",
                "createTime": null,
                "updateTime": null,
                "msgBodyJson": null,
                "msgBody": [
                    {
                        "msgType": "TIMCustomElem",
                        "msgContent": {
                            "Ext": "",
                            "Desc": "",
                            "Data": "{\"msgType\":\"TIMCustomFileElem\",\"msgContent\":{\"title\":\"【分享文件】\",\"fileName\":\"81616467489.jpg\",\"url\":\"https://files.csd.test.v2db.com/auth/auth_1616467490143_2021-03-23_68.jpg\",\"fileType\":\"jpg\",\"fileSize\":312305,\"affixId\":\"51d6e6a9910d4579a8691bf53fe3fb98\",\"downloadFlag\":2}}",
                            "Sound": ""
                        }
                    }
                ]
            }
        ]

**Comment by Tencent-Alice** [comment]
您好，关于您的问题，目前服务端仅支持获取7天内的聊天记录，客户端暂无方法导入聊天记录。
需要您调用服务端接口调入消息，您可以参考以下文档链接。
导入单聊消息：https://cloud.tencent.com/document/product/269/2568 
导入群消息：https://cloud.tencent.com/document/product/269/1635

**Comment by ludaxin6** [comment]
> https://cloud.tencent.com/document/product/269/2568

大佬，你好，我们现在就是按照你给出的地址处理历史聊天数据的，我最想知道的是这个数据我们拿到了怎么整合到客户端代码里？有实现案例或例子不？

**Comment by weinierfei** [comment]
@ludaxin6 哈喽  问下这个后来解决了么?
